-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	[1] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-GENERAL";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 23;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 1;
			["hardwareName"] = "INT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:22:06";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[2] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-GOTEOBAJO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 99;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 24;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 2;
			["hardwareName"] = "INT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 99;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:02:23";
		["rawData"] = {
			[1] = "99";
		};
		["baseType"] = "device";
	};
	[3] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-TURBINAS";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 25;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 3;
			["hardwareName"] = "INT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:22:06";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[4] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-PORCHE";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 27;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 4;
			["hardwareName"] = "INT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:22:06";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[5] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-PATIO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 28;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 5;
			["hardwareName"] = "INT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 99;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:05:23";
		["rawData"] = {
			[1] = "99";
		};
		["baseType"] = "device";
	};
	[6] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-PIEDRAS";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 29;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 6;
			["hardwareName"] = "INT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:22:07";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[7] = {
		["switchTypeValue"] = 0;
		["name"] = "FLUJO AGUA";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Waterflow";
		["timedOut"] = false;
		["id"] = 43;
		["data"] = {
			["_state"] = "0.00";
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareName"] = "INT";
			["icon"] = "moisture";
			["hardwareID"] = 3;
			["protected"] = false;
			["unit"] = 1;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "0000001E";
		["lastUpdate"] = "2018-06-08 22:22:41";
		["rawData"] = {
			[1] = "0.00";
		};
		["baseType"] = "device";
	};
	[8] = {
		["switchTypeValue"] = 2;
		["name"] = "CONTADOR AGUA";
		["description"] = "";
		["switchType"] = "Contact";
		["lastLevel"] = 0;
		["subType"] = "RFXMeter counter";
		["timedOut"] = true;
		["id"] = 44;
		["data"] = {
			["_state"] = "75";
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["protected"] = false;
			["unit"] = 0;
			["_nValue"] = 0;
			["valueUnits"] = "";
			["valueQuantity"] = "";
			["hardwareName"] = "INT";
			["icon"] = "counter";
			["counterToday"] = "74 Liter";
			["counter"] = "0.075 m3";
			["hardwareID"] = 3;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "RFXMeter";
		["signalLevel"] = 12;
		["deviceID"] = "30";
		["lastUpdate"] = "2018-06-08 21:37:22";
		["rawData"] = {
			[1] = "75";
		};
		["baseType"] = "device";
	};
	[9] = {
		["switchTypeValue"] = 0;
		["name"] = "TEMP RPI";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "LaCrosse TX3";
		["timedOut"] = false;
		["id"] = 48;
		["data"] = {
			["temperature"] = 44.400001525879;
			["_state"] = "44.4";
			["hardwareTypeValue"] = 23;
			["hardwareType"] = "Motherboard sensors";
			["_nValue"] = 0;
			["hardwareName"] = "RPI";
			["icon"] = "temperature";
			["unit"] = 1;
			["protected"] = false;
			["hardwareID"] = 4;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Temp";
		["signalLevel"] = 12;
		["deviceID"] = "1";
		["lastUpdate"] = "2018-06-08 22:41:21";
		["rawData"] = {
			[1] = "44.4";
		};
		["baseType"] = "device";
	};
	[10] = {
		["switchTypeValue"] = 0;
		["name"] = "CPU RPI";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Percentage";
		["timedOut"] = false;
		["id"] = 49;
		["data"] = {
			["_state"] = "23.23";
			["hardwareTypeValue"] = 23;
			["hardwareType"] = "Motherboard sensors";
			["_nValue"] = 0;
			["hardwareName"] = "RPI";
			["icon"] = "hardware";
			["hardwareID"] = 4;
			["protected"] = false;
			["unit"] = 1;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "0000044D";
		["lastUpdate"] = "2018-06-08 22:42:11";
		["rawData"] = {
			[1] = "23.23";
		};
		["baseType"] = "device";
	};
	[11] = {
		["switchTypeValue"] = 0;
		["name"] = "UPTIME-INT";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Text";
		["timedOut"] = false;
		["id"] = 52;
		["data"] = {
			["_state"] = "11:2:43 - 0/0/0";
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["_nValue"] = 0;
			["hardwareName"] = "INT";
			["icon"] = "text";
			["hardwareID"] = 3;
			["protected"] = false;
			["unit"] = 1;
		};
		["changed"] = true;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "00000018";
		["lastUpdate"] = "2018-06-08 22:42:05";
		["rawData"] = {
			[1] = "11:2:43 - 0/0/0";
		};
		["baseType"] = "device";
	};
	[12] = {
		["switchTypeValue"] = 9;
		["name"] = "RESET-INT";
		["description"] = "";
		["switchType"] = "Push On Button";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = true;
		["id"] = 53;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 41;
			["hardwareType"] = "MySensors Gateway USB";
			["internalState"] = "Off";
			["_nValue"] = 0;
			["hardwareID"] = 3;
			["unit"] = 9;
			["hardwareName"] = "INT";
			["icon"] = "push";
			["maxDimLevel"] = 100;
			["protected"] = true;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2017-12-31 20:01:13";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[13] = {
		["switchTypeValue"] = 0;
		["name"] = "LUZ PORCHE";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 100;
		["subType"] = "Switch";
		["timedOut"] = false;
		["id"] = 55;
		["data"] = {
			["_state"] = "On";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["_nValue"] = 1;
			["hardwareID"] = 7;
			["unit"] = 1;
			["hardwareName"] = "SONOFF1 SWITCH";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 100;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00014087";
		["lastUpdate"] = "2018-06-08 22:30:03";
		["rawData"] = {
			[1] = "100";
		};
		["baseType"] = "device";
	};
	[14] = {
		["switchTypeValue"] = 11;
		["name"] = "PUERTA COCINA";
		["description"] = "";
		["switchType"] = "Door Contact";
		["lastLevel"] = 0;
		["subType"] = "Switch";
		["timedOut"] = true;
		["id"] = 56;
		["data"] = {
			["_state"] = "Closed";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["internalState"] = "Closed";
			["_nValue"] = 0;
			["hardwareID"] = 8;
			["unit"] = 1;
			["hardwareName"] = "SONOFF1 BUTTON";
			["icon"] = "door";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00014088";
		["lastUpdate"] = "2018-06-04 14:42:40";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[15] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-CUARTILLO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 99;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 58;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 0;
			["hardwareID"] = 9;
			["unit"] = 1;
			["hardwareName"] = "EXT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:22:06";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[16] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-GOTEOALTO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 1;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 59;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 0;
			["hardwareID"] = 9;
			["unit"] = 2;
			["hardwareName"] = "EXT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 99;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:03:23";
		["rawData"] = {
			[1] = "99";
		};
		["baseType"] = "device";
	};
	[17] = {
		["switchTypeValue"] = 0;
		["name"] = "EV-GOTEOOLIVO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 1;
		["subType"] = "AC";
		["timedOut"] = false;
		["id"] = 61;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 0;
			["hardwareID"] = 9;
			["unit"] = 3;
			["hardwareName"] = "EXT";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 99;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2018-06-08 22:04:23";
		["rawData"] = {
			[1] = "99";
		};
		["baseType"] = "device";
	};
	[18] = {
		["switchTypeValue"] = 0;
		["name"] = "UPTIME-EXT";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Text";
		["timedOut"] = false;
		["id"] = 62;
		["data"] = {
			["_state"] = "2:24:58 - 5/0/0";
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 0;
			["hardwareName"] = "EXT";
			["icon"] = "text";
			["hardwareID"] = 9;
			["protected"] = false;
			["unit"] = 1;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "00000018";
		["lastUpdate"] = "2018-06-08 22:42:15";
		["rawData"] = {
			[1] = "2:24:58 - 5/0/0";
		};
		["baseType"] = "device";
	};
	[19] = {
		["switchTypeValue"] = 9;
		["name"] = "RESET-EXT";
		["description"] = "";
		["switchType"] = "Push On Button";
		["lastLevel"] = 0;
		["subType"] = "AC";
		["timedOut"] = true;
		["id"] = 68;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["internalState"] = "Off";
			["_nValue"] = 0;
			["hardwareID"] = 9;
			["unit"] = 9;
			["hardwareName"] = "EXT";
			["icon"] = "push";
			["maxDimLevel"] = 100;
			["protected"] = true;
			["levelVal"] = 100;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "00000000";
		["lastUpdate"] = "2017-05-01 10:13:55";
		["rawData"] = {
			[1] = "100";
		};
		["baseType"] = "device";
	};
	[20] = {
		["switchTypeValue"] = 0;
		["name"] = "HUM CUARTILLO";
		["description"] = "Sensor de humedad de suelo al lado del cuartillo";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Soil Moisture";
		["timedOut"] = false;
		["id"] = 69;
		["data"] = {
			["_state"] = "183";
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 183;
			["hardwareName"] = "EXT";
			["icon"] = "moisture";
			["hardwareID"] = 9;
			["protected"] = false;
			["unit"] = 1;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "0000000A";
		["lastUpdate"] = "2018-06-08 22:42:14";
		["rawData"] = {
		};
		["baseType"] = "device";
	};
	[21] = {
		["switchTypeValue"] = 0;
		["name"] = "TEMP CUARTILLO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "LaCrosse TX3";
		["timedOut"] = false;
		["id"] = 72;
		["data"] = {
			["temperature"] = 22;
			["_state"] = "22.0";
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 0;
			["hardwareName"] = "EXT";
			["icon"] = "temperature";
			["unit"] = 14;
			["protected"] = false;
			["hardwareID"] = 9;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Temp";
		["signalLevel"] = 12;
		["deviceID"] = "14";
		["lastUpdate"] = "2018-06-08 22:42:15";
		["rawData"] = {
			[1] = "22.0";
		};
		["baseType"] = "device";
	};
	[22] = {
		["switchTypeValue"] = 0;
		["name"] = "LUX1-EXT";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Lux";
		["timedOut"] = false;
		["id"] = 74;
		["data"] = {
			["_state"] = "492";
			["hardwareTypeValue"] = 42;
			["hardwareType"] = "MySensors Gateway with LAN interface";
			["_nValue"] = 0;
			["lux"] = 492;
			["hardwareName"] = "EXT";
			["icon"] = "lux";
			["unit"] = 18;
			["protected"] = false;
			["hardwareID"] = 9;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Lux";
		["signalLevel"] = 12;
		["deviceID"] = "0000000";
		["lastUpdate"] = "2018-06-08 22:42:15";
		["rawData"] = {
			[1] = "492";
		};
		["baseType"] = "device";
	};
	[23] = {
		["switchTypeValue"] = 0;
		["name"] = "THB";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "THB1 - BTHR918, BTHGN129";
		["timedOut"] = false;
		["id"] = 79;
		["data"] = {
			["temperature"] = 18.39999961853;
			["_state"] = "18.4;79;3;1013;3";
			["forecastString"] = "Cloudy";
			["hardwareTypeValue"] = 79;
			["forecast"] = 3;
			["hardwareType"] = "AccuWeather (Weather Lookup)";
			["barometer"] = 1013;
			["humidity"] = 79;
			["_nValue"] = 0;
			["unit"] = 1;
			["dewPoint"] = 14.689999580383;
			["hardwareName"] = "TIEMPO";
			["icon"] = "temperature";
			["humidityStatus"] = "Wet";
			["protected"] = false;
			["hardwareID"] = 11;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Temp + Humidity + Baro";
		["signalLevel"] = 12;
		["deviceID"] = "1";
		["lastUpdate"] = "2018-06-08 22:24:53";
		["rawData"] = {
			[1] = "18.4";
			[2] = "79";
			[3] = "3";
			[4] = "1013";
			[5] = "3";
		};
		["baseType"] = "device";
	};
	[24] = {
		["switchTypeValue"] = 0;
		["name"] = "LLUVIA";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "WWW";
		["timedOut"] = false;
		["id"] = 82;
		["data"] = {
			["_state"] = "0;0.0";
			["rainRate"] = 0;
			["hardwareTypeValue"] = 79;
			["hardwareType"] = "AccuWeather (Weather Lookup)";
			["_nValue"] = 0;
			["hardwareID"] = 11;
			["hardwareName"] = "TIEMPO";
			["icon"] = "rain";
			["unit"] = 0;
			["protected"] = false;
			["rain"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Rain";
		["signalLevel"] = 12;
		["deviceID"] = "1";
		["lastUpdate"] = "2018-06-08 22:24:53";
		["rawData"] = {
			[1] = "0";
			[2] = "0.0";
		};
		["baseType"] = "device";
	};
	[25] = {
		["switchTypeValue"] = 0;
		["name"] = "COMPLETO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Switch";
		["timedOut"] = false;
		["id"] = 84;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["_nValue"] = 0;
			["hardwareID"] = 12;
			["unit"] = 1;
			["hardwareName"] = "RIEGOCOMPLETO";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "000140A4";
		["lastUpdate"] = "2018-06-08 21:45:02";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[26] = {
		["switchTypeValue"] = 0;
		["name"] = "CESPED";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Switch";
		["timedOut"] = false;
		["id"] = 86;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["_nValue"] = 0;
			["hardwareID"] = 12;
			["unit"] = 1;
			["hardwareName"] = "RIEGOCOMPLETO";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "000140A6";
		["lastUpdate"] = "2018-06-08 22:41:28";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[27] = {
		["switchTypeValue"] = 0;
		["name"] = "GOTEOS";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Switch";
		["timedOut"] = false;
		["id"] = 87;
		["data"] = {
			["_state"] = "Off";
			["usedByCamera"] = false;
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["_nValue"] = 0;
			["hardwareID"] = 12;
			["unit"] = 1;
			["hardwareName"] = "RIEGOCOMPLETO";
			["icon"] = "lightbulb";
			["maxDimLevel"] = 100;
			["protected"] = false;
			["levelVal"] = 0;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "Light/Switch";
		["signalLevel"] = 12;
		["deviceID"] = "000140A7";
		["lastUpdate"] = "2018-06-08 22:05:23";
		["rawData"] = {
			[1] = "0";
		};
		["baseType"] = "device";
	};
	[28] = {
		["switchTypeValue"] = 0;
		["name"] = "TIEMPO DE RIEGO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Custom Sensor";
		["timedOut"] = false;
		["id"] = 88;
		["data"] = {
			["sensorUnit"] = "minutos";
			["_state"] = "1";
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["_nValue"] = 0;
			["sensorType"] = 1;
			["hardwareName"] = "RIEGOCOMPLETO";
			["icon"] = "Timer";
			["unit"] = 1;
			["protected"] = false;
			["hardwareID"] = 12;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "00082088";
		["lastUpdate"] = "2018-06-08 22:42:01";
		["rawData"] = {
			[1] = "1";
		};
		["baseType"] = "device";
	};
	[29] = {
		["switchTypeValue"] = 0;
		["name"] = "TIEMPO DE PATIO";
		["description"] = "";
		["switchType"] = "On/Off";
		["lastLevel"] = 0;
		["subType"] = "Custom Sensor";
		["timedOut"] = false;
		["id"] = 90;
		["data"] = {
			["sensorUnit"] = "minutos";
			["_state"] = "1";
			["hardwareTypeValue"] = 15;
			["hardwareType"] = "Dummy (Does nothing, use for virtual switches only)";
			["_nValue"] = 0;
			["sensorType"] = 1;
			["hardwareName"] = "RIEGOCOMPLETO";
			["icon"] = "Timer";
			["unit"] = 1;
			["protected"] = false;
			["hardwareID"] = 12;
		};
		["changed"] = false;
		["batteryLevel"] = 255;
		["deviceType"] = "General";
		["signalLevel"] = 12;
		["deviceID"] = "00082090";
		["lastUpdate"] = "2018-06-08 22:42:01";
		["rawData"] = {
			[1] = "1";
		};
		["baseType"] = "device";
	};
	[30] = {
		["id"] = 1;
		["data"] = {
			["value"] = 1;
		};
		["variableType"] = "integer";
		["changed"] = false;
		["name"] = "TIEMPO-RIEGO";
		["lastUpdate"] = "2018-06-04 22:48:02";
		["baseType"] = "uservariable";
	};
	[31] = {
		["id"] = 2;
		["data"] = {
			["value"] = 1;
		};
		["variableType"] = "integer";
		["changed"] = false;
		["name"] = "PATIO-RIEGO";
		["lastUpdate"] = "2018-06-04 22:48:10";
		["baseType"] = "uservariable";
	};
	[32] = {
		["id"] = 3;
		["data"] = {
			["value"] = 582909089;
		};
		["variableType"] = "integer";
		["changed"] = false;
		["name"] = "TelegramBotOffset";
		["lastUpdate"] = "2018-06-08 09:41:37";
		["baseType"] = "uservariable";
	};
	[33] = {
		["id"] = 4;
		["data"] = {
			["value"] = "On";
		};
		["variableType"] = "string";
		["changed"] = false;
		["name"] = "TelegramBotMenu";
		["lastUpdate"] = "2018-06-07 12:37:51";
		["baseType"] = "uservariable";
	};
}
return obj1
